# Generated by Django 2.2.4 on 2021-07-17 06:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myoperations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='操作名称')),
                ('deal_code', models.CharField(default='', max_length=16, verbose_name='业务号')),
                ('from_ips', models.CharField(default='', max_length=100, verbose_name='原始ip')),
                ('to_ips', models.CharField(default='', max_length=100, verbose_name='结果ip')),
                ('operation_time', models.DateTimeField(default=datetime.datetime(2021, 7, 17, 14, 38, 2, 409653), verbose_name='操作时间')),
                ('operator', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
