# Generated by Django 2.2.4 on 2021-07-17 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myoperations', '0002_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='descrption',
            field=models.CharField(default='', max_length=50, verbose_name='操作原因'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='操作名称'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 14, 47, 13, 477176), verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operator',
            field=models.CharField(blank=True, default='', help_text='添加者', max_length=50),
        ),
    ]
