# Generated by Django 2.2.4 on 2021-07-17 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myoperations', '0003_auto_20210717_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='descrption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 14, 53, 0, 854921), verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operator',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='添加者'),
        ),
    ]
