# Generated by Django 2.2.4 on 2021-07-17 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myoperations', '0004_auto_20210717_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 15, 10, 30, 405713), verbose_name='操作时间'),
        ),
    ]
